# 子模块
add_subdirectory(app)
add_subdirectory(core)
add_subdirectory(communication)
add_subdirectory(databus)
add_subdirectory(data)
add_subdirectory(curve)
add_subdirectory(device)
add_subdirectory(parameter)
add_subdirectory(automation)
add_subdirectory(plugin)
add_subdirectory(logging)
add_subdirectory(scripting)
add_subdirectory(ui)